In [21]:
# CBC GRADING 
def cbc_report_generator(df): 
          
    # --- Automates CBC grading, comments and general remarks for a student dataframe of ---; 
    
# 1.CLEANING 
 # fill missing scores with 0 
 df = df.fillna(0)  

 #2.CONVERTING FLOATS TO INT 
 subjectcolumns = [col for col in df.columns if col not in ['Position','NAME','TOTAL']]
 df[subjectcolumns] = df[subjectcolumns].astype(int)  
    
 #3. GRADING     
 def get_grade(score):
    if score >= 89:    return 'EE1'
    elif score >= 74:  return 'EE2' 
    elif score >= 57:  return 'ME1' 
    elif score >= 40:  return 'ME2'
    elif score >= 30:  return 'AE1' 
    elif score >= 20:  return 'AE2'
    elif score >= 10:  return 'BE1' 
    elif score >= 1:   return 'BE2'
    else:              return 'ABSENT' 
 # specifying columns for grading 
 for col in subjectcolumns: 
    df[col] = df[col].apply(get_grade) 

#4. COMMENTS SECTION 
# generating comments
 def get_comment(grade):
    if   'EE' in grade:  return "Exceeding Expectations"
    elif 'ME' in grade:  return "Meeting Expectations"
    elif 'AE' in grade:  return "Approcahing Expectations"
    elif 'BE' in grade:  return 'Below Expectations'
    else :               return "ABSENT" 

# adding a comment column based on learning area 
 for col in subjectcolumns:
    comment_col = col + "_COMMENT"
    df[comment_col] = df[col].apply(get_comment) 
   
#5.  ADDING A GENERAL REMARKS COLUMN 
 def generalcomment(position):    
    if  1 <= position <= 10:                         #SAME AS; If position >= 1 and position <= 10 
        return 'Good work, Keep working hard.'
    elif  11 <= position <= 25: 
        return 'You did well, put more effort in your weak learning areas.'
    elif  26 <= position <= 36:
        return 'You can do better, work harder.'
    elif   37 <= position <= 45: 
        return " There's room for improvement, put more effort."
    else:
        return 'Pull up your socks! You can do better.' 
             
# adding the general remarks column 
 df['GENERAL_COMMENT'] = df['Position'].apply(generalcomment)  

#6. ADD DATES DEPENDING ON TERM DATES
# df['CLOSING_DATE'] = 'YYYY-MM-DD'
# df['OPENING_DATE'] = 'YYYY-MM-DD' 

 return df 

# --- HOW TO USE IT ---; 
# processed_report = cbc_report_generator(df)

In [25]:
import pandas as pd 
df = pd.read_excel(r"C:\Users\ADMIN\OneDrive\Desktop\grade888.xlsx")  

df

,Position,NAME,ENG,KISW,MATHS,INT/SCI,AGRIC,PRETECH,C.A,SST,IRE,TOTAL
0,1,NURU HAMISI,53.0,64.0,45.0,50.0,65.0,52.0,65.0,60.0,88.0,542
1,2,ABDIRAHMAN MAHAMUD,44.0,58.0,75.0,26.0,65.0,58.0,75.0,44.0,90.0,535
2,3,ABDIRAHMAN MUKTAR,50.0,66.0,55.0,48.0,70.0,46.0,55.0,46.0,98.0,534
3,4,ABDIKARIM MOHAMUD,24.0,56.0,70.0,36.0,65.0,50.0,70.0,56.0,94.0,521
4,5,SADAQ MOHAMUD,30.0,62.0,65.0,32.0,60.0,50.0,60.0,62.0,98.0,519
5,6,FARTUN ISMAIL,56.0,60.0,70.0,32.0,50.0,42.0,70.0,40.0,98.0,518
6,7,MAHAD RIYAL,44.0,54.0,65.0,28.0,60.0,54.0,75.0,34.0,90.0,504
7,8,ANAB MUSE,44.0,56.0,65.0,30.0,65.0,54.0,70.0,24.0,94.0,502
8,9,RAHMA YUSSUF,46.0,54.0,70.0,40.0,45.0,46.0,70.0,38.0,92.0,501
9,10,KOWSAR OSMAN,44.0,44.0,70.0,34.0,65.0,44.0,70.0,42.0,86.0,499
10,11,SALAH AHMED,44.0,50.0,65.0,12.0,65.0,44.0,75.0,54.0,88.0,497
11,12,YUSRA HADIJA,58.0,60.0,30.0,40.0,65.0,50.0,60.0,44.0,78.0,485
12,13,RIYAL HASSAN,40.0,44.0,70.0,20.0,70.0,40.0,60.0,42.0,98.0,484
13,13,AMINA MINHAJ,46.0,50.0,65.0,26.0,55.0,50.0,70.0,32.0,90.0,484
14,15,SIYAT MOHAMED,46.0,46.0,60.0,16.0,70.0,54.0,65.0,36.0,90.0,483
15,16,HAFSA KHALIF,48.0,52.0,70.0,24.0,50.0,46.0,70.0,34.0,88.0,482
16,17,ABDIRAHMAN YUSSUF,42.0,54.0,70.0,16.0,55.0,52.0,80.0,26.0,76.0,471
17,18,LUQMAN OSMAN,36.0,48.0,55.0,36.0,55.0,54.0,65.0,34.0,84.0,467
18,19,MOHAMED HASSAN,52.0,54.0,45.0,38.0,65.0,46.0,45.0,42.0,76.0,463
19,19,FARDOSA DEKOW,36.0,50.0,70.0,18.0,65.0,42.0,60.0,36.0,86.0,463
20,21,FARTUN AHMED,32.0,38.0,65.0,24.0,70.0,42.0,60.0,38.0,82.0,451
21,22,SHAMAD ABASS,44.0,40.0,60.0,36.0,60.0,44.0,55.0,36.0,70.0,445
22,23,ANZAL ALI,44.0,34.0,50.0,18.0,60.0,48.0,55.0,36.0,92.0,437
23,24,YUSSUF HUSSEIN,30.0,32.0,65.0,40.0,50.0,48.0,45.0,32.0,86.0,428
24,25,SALIM ABDALLA,26.0,38.0,50.0,26.0,55.0,56.0,60.0,28.0,84.0,423
25,26,ESHA MOHAMED,38.0,60.0,55.0,38.0,45.0,46.0,40.0,34.0,64.0,420
26,27,ATIF BILLOW,16.0,48.0,55.0,16.0,60.0,48.0,50.0,42.0,84.0,419
27,28,MOHAMED AHMED,36.0,36.0,70.0,22.0,55.0,50.0,45.0,26.0,76.0,416
28,29,MUNIR ABUKAR,20.0,36.0,65.0,30.0,70.0,38.0,50.0,34.0,72.0,415
29,30,SUMEYA OSMAN,34.0,38.0,60.0,24.0,55.0,48.0,40.0,22.0,76.0,397
30,30,SARWA BILLOW,44.0,38.0,55.0,24.0,55.0,38.0,45.0,24.0,74.0,397
31,32,ABDIMALIK MAHAMED,28.0,38.0,45.0,14.0,65.0,52.0,35.0,36.0,82.0,395
32,33,FATUMA SAID,34.0,60.0,40.0,30.0,40.0,44.0,35.0,28.0,62.0,373
33,34,MWANAHAMISI MAHAMED,32.0,60.0,30.0,26.0,35.0,48.0,40.0,38.0,60.0,369
34,35,RIYAL AHMED,40.0,36.0,50.0,20.0,45.0,44.0,35.0,36.0,58.0,364
35,36,MARYAN OSMAN,42.0,36.0,NaN,20.0,55.0,44.0,50.0,30.0,86.0,363
36,37,ALI HASSAN,16.0,42.0,30.0,24.0,40.0,46.0,55.0,22.0,44.0,319
37,38,FATUMA MOHAMED,24.0,48.0,30.0,12.0,20.0,46.0,35.0,28.0,52.0,295
38,39,ALI OSMAN,NaN,36.0,NaN,36.0,NaN,NaN,NaN,40.0,NaN,112
39,40,MARYAN MOHAMUD,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,60

In [26]:
# Generate Report 
processed_report = cbc_report_generator(df)

In [27]:
processed_report

,Position,NAME,ENG,KISW,MATHS,INT/SCI,AGRIC,PRETECH,C.A,SST,...,ENG_COMMENT,KISW_COMMENT,MATHS_COMMENT,INT/SCI_COMMENT,AGRIC_COMMENT,PRETECH_COMMENT,C.A_COMMENT,SST_COMMENT,IRE_COMMENT,GENERAL_COMMENT
0,1,NURU HAMISI,ME2,ME1,ME2,ME2,ME1,ME2,ME1,ME1,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,"Good work, Keep working hard."
1,2,ABDIRAHMAN MAHAMUD,ME2,ME1,EE2,AE2,ME1,ME1,EE2,ME2,...,Meeting Expectations,Meeting Expectations,Exceeding Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,Meeting Expectations,Exceeding Expectations,"Good work, Keep working hard."
2,3,ABDIRAHMAN MUKTAR,ME2,ME1,ME2,ME2,ME1,ME2,ME2,ME2,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,"Good work, Keep working hard."
3,4,ABDIKARIM MOHAMUD,AE2,ME2,ME1,AE1,ME1,ME2,ME1,ME2,...,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,"Good work, Keep working hard."
4,5,SADAQ MOHAMUD,AE1,ME1,ME1,AE1,ME1,ME2,ME1,ME1,...,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,"Good work, Keep working hard."
5,6,FARTUN ISMAIL,ME2,ME1,ME1,AE1,ME2,ME2,ME1,ME2,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,"Good work, Keep working hard."
6,7,MAHAD RIYAL,ME2,ME2,ME1,AE2,ME1,ME2,EE2,AE1,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,Approcahing Expectations,Exceeding Expectations,"Good work, Keep working hard."
7,8,ANAB MUSE,ME2,ME2,ME1,AE1,ME1,ME2,ME1,AE2,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"Good work, Keep working hard."
8,9,RAHMA YUSSUF,ME2,ME2,ME1,ME2,ME2,ME2,ME1,AE1,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"Good work, Keep working hard."
9,10,KOWSAR OSMAN,ME2,ME2,ME1,AE1,ME1,ME2,ME1,ME2,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,"Good work, Keep working hard."
10,11,SALAH AHMED,ME2,ME2,ME1,BE1,ME1,ME2,EE2,ME2,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Below Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,Meeting Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
11,12,YUSRA HADIJA,ME1,ME1,AE1,ME2,ME1,ME2,ME1,ME2,...,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
12,13,RIYAL HASSAN,ME2,ME2,ME1,AE2,ME1,ME2,ME1,ME2,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
13,13,AMINA MINHAJ,ME2,ME2,ME1,AE2,ME2,ME2,ME1,AE1,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
14,15,SIYAT MOHAMED,ME2,ME2,ME1,BE1,ME1,ME2,ME1,AE1,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Below Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
15,16,HAFSA KHALIF,ME2,ME2,ME1,AE2,ME2,ME2,ME1,AE1,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
16,17,ABDIRAHMAN YUSSUF,ME2,ME2,ME1,BE1,ME2,ME2,EE2,AE2,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Below Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,Approcahing Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
17,18,LUQMAN OSMAN,AE1,ME2,ME2,AE1,ME2,ME2,ME1,AE1,...,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
18,19,MOHAMED HASSAN,ME2,ME2,ME2,AE1,ME1,ME2,ME2,ME2,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
19,19,FARDOSA DEKOW,AE1,ME2,ME1,BE1,ME1,ME2,ME1,AE1,...,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Below Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
20,21,FARTUN AHMED,AE1,AE1,ME1,AE2,ME1,ME2,ME1,AE1,...,Approcahing Expectations,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
21,22,SHAMAD ABASS,ME2,ME2,ME1,AE1,ME1,ME2,ME2,AE1,...,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,"You did well, put more effort in your weak lea..."
22,23,ANZAL ALI,ME2,AE1,ME2,BE1,ME1,ME2,ME2,AE1,...,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Below Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
23,24,YUSSUF HUSSEIN,AE1,AE1,ME1,ME2,ME2,ME2,ME2,AE1,...,Approcahing Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
24,25,SALIM ABDALLA,AE2,AE1,ME2,AE2,ME2,ME2,ME1,AE2,...,Approcahing Expectations,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"You did well, put more effort in your weak lea..."
25,26,ESHA MOHAMED,AE1,ME1,ME2,AE1,ME2,ME2,ME2,AE1,...,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,"You can do better, work harder."
26,27,ATIF BILLOW,BE1,ME2,ME2,BE1,ME1,ME2,ME2,ME2,...,Below Expectations,Meeting Expectations,Meeting Expectations,Below Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Exceeding Expectations,"You can do better, work harder."
27,28,MOHAMED AHMED,AE1,AE1,ME1,AE2,ME2,ME2,ME2,AE2,...,Approcahing Expectations,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"You can do better, work harder."
28,29,MUNIR ABUKAR,AE2,AE1,ME1,AE1,ME1,AE1,ME2,AE1,...,Approcahing Expectations,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,"You can do better, work harder."
29,30,SUMEYA OSMAN,AE1,AE1,ME1,AE2,ME2,ME2,ME2,AE2,...,Approcahing Expectations,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"You can do better, work harder."
30,30,SARWA BILLOW,ME2,AE1,ME2,AE2,ME2,AE1,ME2,AE2,...,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"You can do better, work harder."
31,32,ABDIMALIK MAHAMED,AE2,AE1,ME2,BE1,ME1,ME2,AE1,AE1,...,Approcahing Expectations,Approcahing Expectations,Meeting Expectations,Below Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Approcahing Expectations,Exceeding Expectations,"You can do better, work harder."
32,33,FATUMA SAID,AE1,ME1,ME2,AE1,ME2,ME2,AE1,AE2,...,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Approcahing Expectations,Meeting Expectations,"You can do better, work harder."
33,34,MWANAHAMISI MAHAMED,AE1,ME1,AE1,AE2,AE1,ME2,ME2,AE1,...,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Approcahing Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,"You can do better, work harder."
34,35,RIYAL AHMED,ME2,AE1,ME2,AE2,ME2,ME2,AE1,AE1,...,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Approcahing Expectations,Meeting Expectations,"You can do better, work harder."
35,36,MARYAN OSMAN,ME2,AE1,ABSENT,AE2,ME2,ME2,ME2,AE1,...,Meeting Expectations,Approcahing Expectations,ABSENT,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Exceeding Expectations,"You can do better, work harder."
36,37,ALI HASSAN,BE1,ME2,AE1,AE2,ME2,ME2,ME2,AE2,...,Below Expectations,Meeting Expectations,Approcahing Expectations,Approcahing Expectations,Meeting Expectations,Meeting Expectations,Meeting Expectations,Approcahing Expectations,Meeting Expectations,"There's room for improvement, put more effort."
37,38,FATUMA MOHAMED,AE2,ME2,AE1,BE1,AE2,ME2,AE1,AE2,...,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Below Expectations,Approcahing Expectations,Meeting Expectations,Approcahing Expectations,Approcahing Expectations,Meeting Expectations,"There's room for improvement, put more effort."
38,39,ALI OSMAN,ABSENT,AE1,ABSENT,AE1,ABSENT,ABSENT,ABSENT,ME2,...,ABSENT,Approcahing Expectations,ABSENT,Approcahing Expectations,ABSENT,ABSENT,ABSENT,Meeting Expectations,ABSENT,"There's room for improvement, put more effort."
39,40,MARYAN MOHAMUD,ABSENT,ABSENT,ME1,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,...,ABSENT,ABSENT,Meeting Expectations,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,ABSENT,"There's room for improvement, put more effort."

In [29]:
processed_report.to_csv("processed_report.csv", index=False)